Title : " Python NumPy"
@ Author : Shivam Goyal

Date : 9 January, 2022

Version 1

https://www.educba.com/numpy-concatenate/?source=leftnav

### Numpy Arrays

Numpy array contains only 1 type of data

In [2]:
import numpy as np
import pandas as pd

In [23]:
# Creating an array

l = np.array([3,2,1])
b = np.array([5.3,6.3,7.4])
c = np.array(['a','b','c'])

In [24]:
l,c

(array([3, 2, 1]), array(['a', 'b', 'c'], dtype='<U1'))

In [25]:
np.array([l,c])
np.array([l,b])

array([[3. , 2. , 1. ],
       [5.3, 6.3, 7.4]])

In [26]:
# NumPy provides the arange function which is analogous to the Python built-in range, but returns an array
m = np.array([[4,2,1],[5,3,1]])
n = np.array([[2,2,2],[2,3,4]])

In [27]:
m,n

(array([[4, 2, 1],
        [5, 3, 1]]),
 array([[2, 2, 2],
        [2, 3, 4]]))

In [28]:
np.sum(m,axis=0),np.sum(m,axis=1), np.sum(m)

(array([9, 5, 2]), array([7, 9]), 16)

In [16]:
np.append(m,n, axis=0)

array([[1, 2, 3],
       [2, 3, 4],
       [2, 2, 2],
       [2, 3, 4]])

In [17]:
np.arange(15,90,5)

array([15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85])

In [19]:
# create an array using arange and reshape
a = np.arange(15,90,5).reshape(3, 5)
a[::-1],a

(array([[65, 70, 75, 80, 85],
        [40, 45, 50, 55, 60],
        [15, 20, 25, 30, 35]]),
 array([[15, 20, 25, 30, 35],
        [40, 45, 50, 55, 60],
        [65, 70, 75, 80, 85]]))

In [31]:
m,np.sort(m)

(array([[4, 2, 1],
        [5, 3, 1]]),
 array([[1, 2, 4],
        [1, 3, 5]]))

In [32]:
np.where(a<30,1,0)

array([[1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# np.sort(np.where(a<30,1,0))
np.ravel(a)

In [34]:
np.concatenate((m,n), axis =1),np.concatenate((m,n), axis =0)

(array([[4, 2, 1, 2, 2, 2],
        [5, 3, 1, 2, 3, 4]]),
 array([[4, 2, 1],
        [5, 3, 1],
        [2, 2, 2],
        [2, 3, 4]]))

In [38]:
# Zero and Ones
# np.ones(3, dtype=np.int32)
# np.zeros((4,4), dtype=np.int32)
np.empty((2, 3)) 

array([[3. , 2. , 1. ],
       [5.3, 6.3, 7.4]])

In [42]:
# 3*4 array
l = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]]).reshape(3,4)
l
# l[2][3]

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [43]:
# Operators on arrays

l**3

array([[  1,   8,  27,  64],
       [  8,  27,  64, 125],
       [ 27,  64, 125, 216]], dtype=int32)

In [47]:
l+l

array([[ 2,  4,  6,  8],
       [ 4,  6,  8, 10],
       [ 6,  8, 10, 12]])

In [50]:
l[l>2]

array([3, 4, 3, 4, 5, 3, 4, 5, 6])

In [51]:
np.sqrt(l)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.41421356, 1.73205081, 2.        , 2.23606798],
       [1.73205081, 2.        , 2.23606798, 2.44948974]])

In [53]:
# Subsetting of arrays can be done same as lists
l[2][2]

5

In [56]:
# Functions on a array

l.ndim

2

In [ ]:
l.sum(axis=1)
l.min(axis=1) 
np.add(l, m)

np.where(l < 5, l, 10*l)

np.sort(arr)

np.concatenate((a, b), axis=0)

l[::-1]  # reversed l

l.T  # returns the array, transposed

l.ravel() 

In [57]:
np.unique(l)

array([1, 2, 3, 4, 5, 6])

In [63]:
np.random.seed(123)
np.random.random((4,4))

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477],
       [0.71946897, 0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426, 0.73799541]])

In [59]:
# Create a 2D array using matrix function
np.matrix([[1,2,3],[2,3,4]])

matrix([[1, 2, 3],
        [2, 3, 4]])

In [65]:
np.ndarray(shape =(3,5), dtype=int)

array([[         0,          0,          0,          0,          0],
       [         0,          0,          0,          0,          0],
       [      2524,          0,          0, 1886323546,          0]])

In [66]:
A = np.ndarray(shape=(2,2), dtype=int)
print("Array with random values:\n", A)

Array with random values:
 [[16843009 16843009]
 [16843009 16843009]]


In [44]:
#creating an array with buffer
G = np.ndarray((3,2), buffer=np.array([1,5,3,4,5,6]),dtype=int)
A = np.ndarray((2,2), buffer=np.array([2,3,7,8]),dtype=int)

In [45]:
G**3

array([[  1, 125],
       [ 27,  64],
       [125, 216]], dtype=int32)

##### Operations on Arrays

In [10]:
# Mathematical operations on Arrays
G + A, G-A, G**2

(array([[  -82511314, -1843070821],
        [  801092659,   288523256]]),
 array([[  82511316, 1843070831],
        [-801092653, -288523248]]),
 array([[ 1, 25],
        [ 9, 16]], dtype=int32))

In [67]:
x = [1, 4, 8, 10, 12]
np.mean(x),np.median(x)
# np.mean(G)

(7.0, 8.0)

In [49]:
G

array([[1, 5],
       [3, 4],
       [5, 6]])

In [55]:
# Where condition for arrays for filtering
G[np.where(G>3)]
G[G>3]

array([5, 4, 5, 6])

In [59]:
# replace an element in array based on condition
np.where(G>3,1,0)  

array([[0, 1],
       [0, 1],
       [1, 1]])

In [24]:
# Joining 2 or more arrays
# np.concatenate((G,A,G), axis = 0) # rowbind
np.concatenate((G,A,G), axis = 1) # cbind


array([[          1,           5,   -82511315, -1843070826,           1,
                  5],
       [          3,           4,   801092656,   288523252,           3,
                  4]])

In [15]:
# Transposing an array
G.T

array([[1, 3],
       [5, 4]])

In [16]:
## Adding an elementor an array to array
np.append(G,A, axis=1),np.insert(G,0,2, axis=1)

(array([[          1,           5,   -82511315, -1843070826],
        [          3,           4,   801092656,   288523252]]),
 array([[2, 1, 5],
        [2, 3, 4]]))

In [69]:
# Deleting elements from an array
np.delete(b,1)

array([5.3, 7.4])

In [18]:
# ravel function is used to flatten or present the data given in a linear manner
np.ravel(np.append(G,A, axis=1),order='C')

array([          1,           5,   -82511315, -1843070826,           3,
                 4,   801092656,   288523252])

In [32]:
G.shape

(2, 2)

In [19]:
G.reshape(-1)

array([1, 5, 3, 4])

In [27]:
################ Random Number Generators

np.random.seed()
# np.random.rans()
# np.random.randint(0,2)

seed(): sets the random seed, so that your results are the reproducible
 between simulations. As an argument, 
it takes an integer of your choosing. 
If you call the function, no output will be generated.


rand(): if you don't specify any arguments, 
it generates a random float between zero and one.

In [30]:
# Set the seed
np.random.seed(123)

# Generate and print random float
print(np.random.rand())

0.6964691855978616


In [71]:
np.random.randn(20,3)
np.linspace(10,20,50)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])